---
abstract: "Use built-in PostgreSQL 'LISTEN' and 'NOTIFY' commands for message-passing."
author:
  - 'Mischa Spiegelmock, C<< <revmischa at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyMQ-Pg
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  AnyEvent::Pg: 0.04
  AnyMQ: 0.30
  JSON: 0
  Test::More: 0
  Try::Tiny: 0
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/revmischa/anymq-pg.git
version: 0.01
